# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cryo_pb2 as cryo__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cryo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CryoEngineStub(object):
    """── Service ───────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FastStep = channel.unary_unary(
                '/cryo.CryoEngine/FastStep',
                request_serializer=cryo__pb2.FastStepRequest.SerializeToString,
                response_deserializer=cryo__pb2.FastStepResponse.FromString,
                _registered_method=True)
        self.GetReport = channel.unary_unary(
                '/cryo.CryoEngine/GetReport',
                request_serializer=cryo__pb2.ReportRequest.SerializeToString,
                response_deserializer=cryo__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/cryo.CryoEngine/CreateSession',
                request_serializer=cryo__pb2.Empty.SerializeToString,
                response_deserializer=cryo__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.SetControl = channel.unary_unary(
                '/cryo.CryoEngine/SetControl',
                request_serializer=cryo__pb2.ControlRequest.SerializeToString,
                response_deserializer=cryo__pb2.Empty.FromString,
                _registered_method=True)


class CryoEngineServicer(object):
    """── Service ───────────────────────────────────────────────────

    """

    def FastStep(self, request, context):
        """Principal endpoint for high-frequency RL steps
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReport(self, request, context):
        """Get full engine metrics and consolidation logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetControl(self, request, context):
        """Dynamic Control (Frozen mode, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CryoEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FastStep': grpc.unary_unary_rpc_method_handler(
                    servicer.FastStep,
                    request_deserializer=cryo__pb2.FastStepRequest.FromString,
                    response_serializer=cryo__pb2.FastStepResponse.SerializeToString,
            ),
            'GetReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReport,
                    request_deserializer=cryo__pb2.ReportRequest.FromString,
                    response_serializer=cryo__pb2.ReportResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=cryo__pb2.Empty.FromString,
                    response_serializer=cryo__pb2.SessionResponse.SerializeToString,
            ),
            'SetControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControl,
                    request_deserializer=cryo__pb2.ControlRequest.FromString,
                    response_serializer=cryo__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cryo.CryoEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cryo.CryoEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CryoEngine(object):
    """── Service ───────────────────────────────────────────────────

    """

    @staticmethod
    def FastStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cryo.CryoEngine/FastStep',
            cryo__pb2.FastStepRequest.SerializeToString,
            cryo__pb2.FastStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cryo.CryoEngine/GetReport',
            cryo__pb2.ReportRequest.SerializeToString,
            cryo__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cryo.CryoEngine/CreateSession',
            cryo__pb2.Empty.SerializeToString,
            cryo__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cryo.CryoEngine/SetControl',
            cryo__pb2.ControlRequest.SerializeToString,
            cryo__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
