# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cryo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cryo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncryo.proto\x12\x04\x63ryo\"\x1c\n\nFloatArray\x12\x0e\n\x06values\x18\x01 \x03(\x02\">\n\x08UnitData\x12\x0f\n\x07unit_id\x18\x01 \x01(\t\x12!\n\x07z_state\x18\x02 \x01(\x0b\x32\x10.cryo.FloatArray\"\xe5\x01\n\x0f\x46\x61stStepRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12>\n\rstate_updates\x18\x03 \x03(\x0b\x32\'.cryo.FastStepRequest.StateUpdatesEntry\x12&\n\x0eregister_units\x18\x04 \x03(\x0b\x32\x0e.cryo.UnitData\x1a\x45\n\x11StateUpdatesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.cryo.FloatArray:\x02\x38\x01\"P\n\x10\x46\x61stStepResponse\x12\x10\n\x08surprise\x18\x01 \x01(\x02\x12\x14\n\x0c\x61\x63tive_units\x18\x02 \x01(\x05\x12\x14\n\x0ctrigger_slow\x18\x03 \x01(\x08\"4\n\rReportRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"%\n\x0eReportResponse\x12\x13\n\x0bjson_report\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"E\n\x0e\x43ontrolRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06\x66rozen\x18\x03 \x01(\x08\"%\n\x0fSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t2\xe5\x01\n\nCryoEngine\x12\x39\n\x08\x46\x61stStep\x12\x15.cryo.FastStepRequest\x1a\x16.cryo.FastStepResponse\x12\x36\n\tGetReport\x12\x13.cryo.ReportRequest\x1a\x14.cryo.ReportResponse\x12\x33\n\rCreateSession\x12\x0b.cryo.Empty\x1a\x15.cryo.SessionResponse\x12/\n\nSetControl\x12\x14.cryo.ControlRequest\x1a\x0b.cryo.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cryo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FASTSTEPREQUEST_STATEUPDATESENTRY']._loaded_options = None
  _globals['_FASTSTEPREQUEST_STATEUPDATESENTRY']._serialized_options = b'8\001'
  _globals['_FLOATARRAY']._serialized_start=20
  _globals['_FLOATARRAY']._serialized_end=48
  _globals['_UNITDATA']._serialized_start=50
  _globals['_UNITDATA']._serialized_end=112
  _globals['_FASTSTEPREQUEST']._serialized_start=115
  _globals['_FASTSTEPREQUEST']._serialized_end=344
  _globals['_FASTSTEPREQUEST_STATEUPDATESENTRY']._serialized_start=275
  _globals['_FASTSTEPREQUEST_STATEUPDATESENTRY']._serialized_end=344
  _globals['_FASTSTEPRESPONSE']._serialized_start=346
  _globals['_FASTSTEPRESPONSE']._serialized_end=426
  _globals['_REPORTREQUEST']._serialized_start=428
  _globals['_REPORTREQUEST']._serialized_end=480
  _globals['_REPORTRESPONSE']._serialized_start=482
  _globals['_REPORTRESPONSE']._serialized_end=519
  _globals['_EMPTY']._serialized_start=521
  _globals['_EMPTY']._serialized_end=528
  _globals['_CONTROLREQUEST']._serialized_start=530
  _globals['_CONTROLREQUEST']._serialized_end=599
  _globals['_SESSIONRESPONSE']._serialized_start=601
  _globals['_SESSIONRESPONSE']._serialized_end=638
  _globals['_CRYOENGINE']._serialized_start=641
  _globals['_CRYOENGINE']._serialized_end=870
# @@protoc_insertion_point(module_scope)
